export enum RoleEnum {
  SYSTEM_MANAGEMENT = 'SYSTEM_MANAGEMENT',
  HR_MANAGEMENT = 'HR_MANAGEMENT',
  HR_ADMIN = 'HR_ADMIN',
  HR_CB = 'HR_CB',
  HR_RECRUITMENT = 'HR_RECRUITMENT',
  HR_TRAINING = 'HR_TRAINING',
  HR_PAYROLL = 'HR_PAYROLL',
}
